Chef.create(name: 'Gordon Ramsey', category: 'French', price: 120, description: 'As a reality television personality, Ramsay is known for his bluntness, as well as fiery temper, strict demeanour, and frequent use of profanity.', user_id: 1, photo: 'https://p2d7x8x2.stackpathcdn.com/content/uploads/2020/10/Gordon-Ramsay-Image-1-scaled-e1603473315103.jpg')
Chef.create(name: 'Marco-Pierre White', category: 'French', price: 95, description: "Marco Pierre White has been known as the enfant terrible of modern gastronomy - a cliché that has been with him for a long time. But the title is no exaggeration for a prodigy who once run Harveys, one of England's most iconic restaurants, and who worked with acclaimed chefs such as Gordon Ramsay, Heston Blumenthal, and Robert Reid. At 33, he became the youngest chef to be awarded three Michelin stars", user_id: 1, photo: 'https://www.finedininglovers.com/sites/g/files/xknfdk626/files/styles/im_square_33/public/Marco-Pierre-White.jpg.webp?itok=lsiO1YWM')
Chef.create(name: 'Jaime Oliver', category: 'Healthy', price: 45, description: 'A simp for health food. The coward of cooking, but still pretty good.', user_id: 1, photo: 'https://i.guim.co.uk/img/media/1988f5a3d0873bb81b670ce73d7afb9be153e7fd/0_155_3000_1800/master/3000.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=69ba3cf51a4f21e311f5b7376c6931a1')
Chef.create(name: 'Heston Blumenthal', category: 'Gastronomic Alchemy', price: 200, description: '', user_id: 1, photo: 'https://hashtaglegend.com/storage/app/media/Article%20Images/epicurious0517-blumenthal-2.jpg')
Chef.create(name: 'Guy Fieri', category: 'Spicy', price: 20, description: 'Such a great guy and makes some amazing food. Just a top notch lad.', user_id: 1, photo: 'https://media.gq.com/photos/59dfc6d9d61cb80476584e18/1:1/w_676,h_676,c_limit/guy-fieiri-flame.jpg')
Chef.create(name: 'Nigella Lawson', category: 'Baked Goods and Butter', price: 60, description: 'Butter... Butter, BUTTER! SO MUCH BUTTER HOW IS SHE ALIVE?', user_id: 1, photo: 'https://pbs.twimg.com/profile_images/1381643668482838531/3ar5XyHk_400x400.jpg')
Chef.create(name: 'Alton Brown', category: 'American Southern', price: 25, description: 'He worked with Mythbusters so he can cook a lasagna in a washing machine, so you do not need all the top notch gear because he can improvise', user_id: 1, photo: 'https://food.fnr.sndimg.com/content/dam/images/food/editorial/talent/alton-brown/FN-TalentAvatar-Alton-Brown.jpg.rend.hgtvcom.616.616.suffix/1532979092729.jpeg')
Chef.create(name: 'Martha Stewart', category: 'Baked Goods', price: 40, description: 'She will probably be high when cooking but there is a chance that she will invite Snoop Dogg over so I guess you can take you chances here. But she has pretty fantastic food.', user_id: 1, photo: 'https://media.self.com/photos/60df3d8c11cf3ada53f4949c/4:3/w_3647,h_2735,c_limit/1209597225')
Chef.create(name: 'Remi the Rat', category: 'French', price: 10, description: 'Look... yes it is a rat... but! This rat has the ability to control human beings with hair tugs so there is something magical with that so maybe the food is magical too?', user_id: 1, photo: 'https://static01.nyt.com/images/2020/11/22/multimedia/00xp-ratatouille/00xp-ratatouille-articleLarge.jpg?quality=75&auto=webp&disable=upscale')
Chef.create(name: 'Jiro Ono', category: 'Japanese Sushi', price: 250, description: 'Sushi that will blow your mind! It is made with such care and delicacy that you are sure to have the experience of a lifetime', user_id: 1, photo: 'https://pyxis.nymag.com/v1/imgs/e64/e5c/0a75b41e86f043a00cd3ccd17246cab571-jiro-dreams-of-sushi.rsquare.w700.jpg')
Chef.create(name: 'Carl Casper', category: 'South American', price: 20, description: 'Amazing cubanos and other Mexican and Southern American foods full of flavour and character', user_id: 1, photo: 'https://pbs.twimg.com/profile_images/487445516142129152/QhjTUAwx_400x400.jpeg')
Chef.create(name: 'Hannibal Lecter', category: 'International', price: 100, description: 'A devilish cook sure to make you a meal that you will ever forget! Speciality in white meats and organs.', user_id: 1, photo: 'http://www.popculturebeast.com/wp-content/uploads/2015/08/Hannibal-Cooking.jpg')


 puts'file seeded'
